language: python

python:
  - "3.5"

install:
  - pwd
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -U pytest-cov
  - pip install codecov

script:
  - pytest --cov

after_success:
   - coveralls
   - codecov
