language: python

python:
  - "3.5"

install:
  - pwd
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=riscv -m py.test -s

after_success:
   - coveralls
