CSR_ADDR_WIDTH     = 12
CSR_COUNTER_WIDTH  = 64

CSR_ADDR_CYCLE     = int('C00',16)
CSR_ADDR_TIME      = int('C01',16)
CSR_ADDR_INSTRET   = int('C02',16)
CSR_ADDR_CYCLEH    = int('C80',16)
CSR_ADDR_TIMEH     = int('C81',16)
CSR_ADDR_INSTRETH  = int('C82',16)
CSR_ADDR_MCPUID    = int('F00',16)
CSR_ADDR_MIMPID    = int('F01',16)
CSR_ADDR_MHARTID   = int('F10',16)
CSR_ADDR_MSTATUS   = int('300',16)
CSR_ADDR_MTVEC     = int('301',16)
CSR_ADDR_MTDELEG   = int('302',16)
CSR_ADDR_MIE       = int('304',16)
CSR_ADDR_MTIMECMP  = int('321',16)
CSR_ADDR_MTIME     = int('701',16)
CSR_ADDR_MTIMEH    = int('741',16)
CSR_ADDR_MSCRATCH  = int('340',16)
CSR_ADDR_MEPC      = int('341',16)
CSR_ADDR_MCAUSE    = int('342',16)
CSR_ADDR_MBADADDR  = int('343',16)
CSR_ADDR_MIP       = int('344',16)
CSR_ADDR_CYCLEW    = int('900',16)
CSR_ADDR_TIMEW     = int('901',16)
CSR_ADDR_INSTRETW  = int('902',16)
CSR_ADDR_CYCLEHW   = int('980',16)
CSR_ADDR_TIMEHW    = int('981',16)
CSR_ADDR_INSTRETHW = int('982',16)

CSR_ADDR_TO_HOST   = int('780',16)
CSR_ADDR_FROM_HOST = int('781',16)

CSR_CMD_WIDTH = 3
CSR_IDLE      = 0
CSR_READ      = 4
CSR_WRITE     = 5
CSR_SET       = 6
CSR_CLEAR     = 7

ECODE_WIDTH                      = 4
ECODE_INST_ADDR_MISALIGNED       = 0
ECODE_INST_ADDR_FAULT            = 1
ECODE_ILLEGAL_INST               = 2
ECODE_BREAKPOINT                 = 3
ECODE_LOAD_ADDR_MISALIGNED       = 4
ECODE_LOAD_ACCESS_FAULT          = 5
ECODE_STORE_AMO_ADDR_MISALIGNED  = 6
ECODE_STORE_AMO_ACCESS_FAULT     = 7
ECODE_ECALL_FROM_U               = 8
ECODE_ECALL_FROM_S               = 9
ECODE_ECALL_FROM_H               = 10
ECODE_ECALL_FROM_M               = 11

ICODE_SOFTWARE = 0
ICODE_TIMER    = 1

PRV_WIDTH     = 2
PRV_U         = 0
PRV_S         = 1
PRV_H         = 2
PRV_M         = 3


# Platform constants 
N_EXT_INTS = 24
