HASTI_BUS_WIDTH = 32
HASTI_BUS_NBYTES = 4
HASTI_ADDR_WIDTH = 32

HASTI_TRANS_WIDTH = 2
HASTI_TRANS_IDLE = 0
HASTI_TRANS_BUSY = 1
HASTI_TRANS_NONSEQ = 2
HASTI_TRANS_SEQ = 3

HASTI_PROT_WIDTH = 4
HASTI_NO_PROT = 0

HASTI_BURST_WIDTH = 3
HASTI_BURST_SINGLE = 0

HASTI_MASTER_NO_LOCK = 0

HASTI_RESP_WIDTH = 1
HASTI_RESP_OKAY = 0
HASTI_RESP_ERROR = 1

HASTI_SIZE_WIDTH = 3
HASTI_SIZE_BYTE = 0
HASTI_SIZE_HALFWORD = 1
HASTI_SIZE_WORD = 2
